# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    FiveOrgsTradeOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *TradeOrdererOrg
        Consortiums:
            TradeConsortium:
                Organizations:
                    - *ExporterOrg
                    - *ImporterOrg
                    - *CarrierOrg
                    - *RegulatorOrg
                    - *BankOrg
    FiveOrgsTradeChannel:
        Consortium: TradeConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ExporterOrg
                - *ImporterOrg
                - *CarrierOrg
                - *RegulatorOrg
                - *BankOrg
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &TradeOrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: TradeOrdererOrg

        # ID to load the MSP definition as
        ID: TradeOrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/trade.com/msp

    - &ExporterOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ExporterOrgMSP

        # ID to load the MSP definition as
        ID: ExporterOrgMSP

        MSPDir: crypto-config/peerOrganizations/exporterorg.trade.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.exporterorg.trade.com
              Port: 7051

    - &ImporterOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ImporterOrgMSP

        # ID to load the MSP definition as
        ID: ImporterOrgMSP

        MSPDir: crypto-config/peerOrganizations/importerorg.trade.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.importerorg.trade.com
              Port: 7051

    - &CarrierOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: CarrierOrgMSP

        # ID to load the MSP definition as
        ID: CarrierOrgMSP

        MSPDir: crypto-config/peerOrganizations/carrierorg.trade.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.carrierorg.trade.com
              Port: 7051

    - &RegulatorOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: RegulatorOrgMSP

        # ID to load the MSP definition as
        ID: RegulatorOrgMSP

        MSPDir: crypto-config/peerOrganizations/regulatororg.trade.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.regulatororg.trade.com
              Port: 7051

    - &BankOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: BankOrgMSP

        # ID to load the MSP definition as
        ID: BankOrgMSP

        MSPDir: crypto-config/peerOrganizations/bankorg.trade.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.bankorg.trade.com
              Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.trade.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:
################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
